fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "ID del Video de YouTube", name: "youtube_id", widget: "string", hint: "Solo el código final del link, ej: dQw4w9WgXcQ", required: false }
      - { label: "Relato", name: "body", widget: "markdown" }
