fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen de Portada", name: "image", widget: "image", required: false }
      - { label: "ID del Video de YouTube", name: "youtube_id", widget: "string", hint: "Solo el código final", required: false }
      - { label: "Relato", name: "body", widget: "markdown" }
